Repository leapfrogtechnology/datamegh, pull requests merged in 2020-02, with the labels that each got.

#2 Configure travis to run tests
  .travis.yml
Labels: ci, test

#4 Add tests for dict_to_list utility function
  datamegh/util/object.py
  tests/util/test_object.py
Labels: test

#8 Setup Black formatter tool and integrate it in CI
  .pre-commit-config.yaml
  .travis.yml
  Makefile
  README.md
  datamegh/__init__.py
  datamegh/constants/common.py
  datamegh/util/db.py
  datamegh/util/fs.py
  datamegh/util/logging.py
  datamegh/util/object.py
  datamegh/util/types.py
  setup.py
  tests/util/test_db.py
  tests/util/test_fs.py
  tests/util/test_object.py
  tests/util/test_types.py
Labels: aesthetics, ci

#5 Setup pyRight for type checking
  .gitignore
  .travis.yml
  Makefile
  datamegh/__init__.py
  package-lock.json
  package.json
  pyrightconfig.json
  typings/.gitkeep
Labels: ci, static typing

#10 Containerize all the checks under the "test" stage
  .travis.yml
  Dockerfile
  Makefile
Labels: ci

#11 Add unit tests for the with_only function
  datamegh/util/object.py
  tests/util/test_object.py
Labels: test

#13 Add unit tests for without_attr function
  tests/util/test_object.py
Labels: test

#17 Add a default help script in Makefile
  Makefile
Labels: enhancement, internals

#9 Configure Travis Deployment to create a release with Pre-Release Enabled
  .travis.yml
  Makefile
Labels: ci, release

#22 Add list_to_dict util to convert list to dictionary with custom keys
  datamegh/util/object.py
  tests/util/test_object.py
Labels: enhancement
